/**
 * This code was generated by Builder.io.
 */
import React from "react";

const OurJourney = () => {
  return (
    <section className="py-16 bg-[#f0f8ff]">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold text-center mb-8">The Journey</h2>
        <p className="text-lg text-center max-w-3xl mx-auto">
          My story began with a deep love for animals and a vision to create a sanctuary where pets receive the utmost care and affection. From humble beginnings, I have grown into a trusted pet care provider, marked by my unwavering commitment to excellence and my enduring love for animals.
        </p>
      </div>
    </section>
  );
};

export default OurJourney;
