/**
 * This code was generated by Builder.io.
 */
import React from "react";

const teamMembers = [
  
  {
    name: "Pamela Marbett",
    role: "Founder & Head Pet Carer",
    image: "/images/8.png",
  },
];

const TeamSection = () => {
  return (
    <section id="team" className="py-16 bg-white">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold text-center mb-8">Meet Me</h2>
        <p className="text-lg text-center max-w-3xl mx-auto mb-12">
          I’m Pamela Marbett, and with over 20 years of experience, I offer licensed, insured, and CPR/First Aid certified pet care in Seattle, Washington.
        </p>
        <p className="text-lg text-center max-w-3xl mx-auto mb-12">
           From daily walks and special needs care to pet sitting and overnight stays, I ensure each pet receives personalized attention and care. Book your spot today and give your pet the pampering they deserve!
        </p>
        <div className="flex flex-col items-center ">
          {teamMembers.map((member, index) => (
            <div
              key={index}
              className="bg-[#f0f8ff] rounded-lg shadow-md overflow-hidden"
            >
              <img
                src={member.image}
                alt={member.name}
                className="w-64  mt-4 p-4 h-64 "
              />

              {/* w-full h-64 object-cover" */}
              <div className="p-6">
                <h3 className="text-xl font-bold mb-2">{member.name}</h3>
                <p className="text-gray-600">{member.role}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default TeamSection;
