/**
 * This code was generated by Builder.io.
 */
import axios from "axios";

const API_BASE_URL = "http://localhost:5050/api/bookings";

const bookingService = {
  createBooking: async (bookingData) => {
    try {
      const response = await axios.post(`${API_BASE_URL}/create`, bookingData);
      return response.data;
    } catch (error) {
      console.error("Error creating booking:", error);
      throw error;
    }
  },

  getAllBookings: async () => {
    try {
      const response = await axios.get(`${API_BASE_URL}/getall`);
      return response.data;
    } catch (error) {
      console.error("Error fetching bookings:", error);
      throw error;
    }
  },

  removeABooking: async (id) => {
    try {
      const response = await axios.delete(`${API_BASE_URL}/delete/${id}`);
      return response.data;
    } catch (error) {
      console.error("Error deleting booking:", error);
      throw error;
    }
  },

  updateBooking: async (id, bookingData) => {
    try {
      const response = await axios.put(
        `${API_BASE_URL}/update/${id}`,
        bookingData
      );
      return response.data;
    } catch (error) {
      console.error("Error updating booking:", error);
      throw error;
    }
  },
};

export default bookingService;
