/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import { HashLink as Link } from 'react-router-hash-link';
import ServiceGrid from "./ServiceGrid";

import FAQSection from "../faq/FAQSection";
import BookASpot from "./BookASpot";

const ServicesPage = () => {
  

  return (
    <div className="bg-[#f0f8ff] min-h-screen">
      <section className="bg-gray-800 text-white text-center py-20">
      <div className="container mx-auto px-4">
        <h1 className="text-5xl font-bold mt-4 mb-4">
          My Services
        </h1>
        <p className="text-xl mb-8">
         The only service in washington that treats your animals as family.
        </p>
        <Link smooth to='#faq' className="bg-[#40bfe0] text-white px-6 py-3 rounded-full hover:bg-[#3aa8c7] transition duration-300">
          Learn More
        </Link>
      </div>
    </section>

      {/* <ServiceCategories /> */}

      <ServiceGrid  />
      <BookASpot />
      <div id="faq">
      <FAQSection />
      </div>

    

      <div className="fixed bottom-0 left-0 right-0 bg-white shadow-lg p-4 flex  justify-center space-x-4">
        <Link to="/booking-form">
        <button className="bg-[#40bfe0] text-gray-800 px-6 py-2 rounded-full hover:bg-[#1e778e] hover:text-gray-100 transition duration-300">
          Book Now
        </button>
        </Link>

        <Link to="/contact">
        <button className="bg-gray-800 text-white px-6 py-2 rounded-full hover:bg-[#1e778e] hover:text-gray-100 transition duration-300">
          Contact
        </button>
        </Link>
      </div>
    </div>
  );
};

export default ServicesPage;
