/**
 * This code was generated by Builder.io.
 */

import React, { useState } from "react";

import Tab from "./Tab";
import VideoPlayer from "./VideoPlayer";
import VideoThumbnail from "./VideoThumbnail";
import PhotoThumbnail from "./PhotoThumbnail";
import Testimonial from "./Testimonial";
import Modal from "./Modal";
import teachingthedogstoswimwebm from '/videos/teachingthedogstoswimwebm.webm'
// import fullherovideo from '/videos/fullherovideo.mp4';
import teachingdogstoswimwebmposter from '/images/teachingdogstoswimwebmposter.png'
import { PlayIcon, CameraIcon } from "@heroicons/react/solid";

const OurWorkInAction = () => {
  const [activeTab, setActiveTab] = useState("videos");
  const [modalContent, setModalContent] = useState(null);

  const sliderSettings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 10000,
  };

 const videos = [
    {
      id: 1,
      src: '/videos/doggievideo.mp4',
      title: "Comfort and Care on the Go",
      description: " Two adorable dogs, clad in stylish red sweaters, enjoy a cozy ride in the backseat of my vehicle. This scene captures the essence of my pet care services in Seattle, Washington – ensuring every pet feels loved and pampered even while traveling. It’s not just about getting from A to B; it’s about doing so with comfort, safety, and a touch of luxury for your furry friends.",
      poster: '/images/doggievideoposter.png'
    },
    {
      id: 2,
      src: '/videos/dogbathingg.mp4', // Ensure this path is correct
      title: "Lola’s Spa Day at Marymoor Off-Leash Dog Park",
      description: "Lola a refreshing bath at the WashSpot after her fun-filled visit with her dog buddies at Marymoor Off-Leash Dog Park. At Pamela’s Pampered Pets, I ensure that every pet enjoys both playtime and pampering. My dedicated pet care services provide your furry friends with the best care, making sure they are clean, happy, and healthy after their adventures.",
      poster:'/images/dogbathing.gif'
    },
    {
      id: 3,
      src: '/videos/conure.mp4',
      title: "Jo's Playtime.",
      description: "A delightful scene featuring a vibrant green and blue hooded conure savoring a treat, showcasing the personalized and attentive care I provide. My approach ensures that every bird feels safe, loved, and well-cared for. Experience the dedication and expertise that make Pamela’s Pampered Pets a sanctuary for your feathered friends.",
      poster: '/images/conure.gif'
      
    },
    
    {
      id: 4,
      src: '/videos/doggyicecreamm.mp4',
      title: "Doggy Delight: Ice Cream Treat Time",
      description: "This image captures a moment of connection and trust between the pet and myself during a car ride. It highlights the exceptional pet care services I provided, ensuring that every journey is safe, comfortable, and enjoyable for your furry friends.",
      poster: '/images/doggyicecream.gif'
      
    },
    {
      id: 5,
      src: '/videos/bird.mp4',
      title: "Jo's Playtime.",
      description: "A vibrant green and blue hooded conure perched comfortably, showing a bond of trust and care it shares with me. At Pamela’s Pampered Pets, I ensure that every bird receives personalized attention and top-notch care, making each moment special and stress-free.",
      poster: '/images/birdposter.gif'
      
    },
    {
      id: 6,
      src: '/videos/happydog.webm',
      title: "Playful Pooches at Pamela’s Pampered Pets",
      description: "Witness the joy and energy of this dog as it enjoys playtime in a spacious, fenced outdoor area. The footage shows the dogs are happy about the care and services provided, ensuring each pet experiences fun, exercise, and socialization in a safe environment",
      poster: '/images/happydoggif.gif'  
      
    },
    {
      id: 7,
      src: '/videos/teachingdogstoswim1.mp4',
      title: "Seaside Serenity at Pamela’s Pampered Pets",
      description: "A dog perched on a log of wood by the water, enjoying the great outdoors. At Pamela’s Pampered Pets, I ensure that every pet gets to explore and enjoy nature safely. My dedicated pet care services provide your furry friends with the attention and care they deserve, making every adventure a joyful and secure experience",
      poster: '/images/dogonlogofwood.gif'  
      
    },
    {
      id: 8,
      src: '/videos/acrobaticdoggy.mp4',
      title: "Companionship in Every Step",
      description: "Set against the lush greenery of Seattle, Washington, this video shows a delightful moment between two furry friends under my care. A golden-coated dog and a fluffy white companion enjoy a playful encounter during their walk, exemplifying the joy and socialization I provide for every pet. It’s not just a service; it’s where pets find happiness and companionship in their daily routines.",
      poster: '/images/acrobaticdoggy.gif'  
      
    },
    
    {
      id: 9,
      src: '/videos/parrot.mp4',
      title: "Feathered Companionship at Pamela’s Pampered Pets",
      description: "Capturing the close bond and trust I share with Jo. I specialize in providing personalized and attentive care for your feathered friends. My expert handling ensures that every bird feels safe, loved, and well-cared for, making each interaction a positive and stress-free experience.",
      poster: '/images/parrot.png'  
      
    },
    {
      id: 10,
      src: '/videos/dogshowling.mp4',
      title: "KIAH, Boomer, and Charlie on duty.",
      description: "KIAH, Boomer, and Charlie, three vigilant dogs, keeping a watchful eye from the window. While their mom and dad are away, these loyal protectors ensure the safety of their home. I understand the importance of security and companionship, providing top-notch pet care services that give you peace of mind knowing your furry friends are well looked after.",
      poster: '/images/dogshowling.gif'  
      
    },
    {
      id: 11,
      src: '/videos/winstonwatchinghummingbirds.webm',
      title: "Winston Watching Hummingbird at their Feeder",
      description: "A cozy indoor scene featuring winston lying on a bed near a window, looking back towards the camera. Outside the window, vibrant fall foliage in shades of yellow, orange, and red surrounds a neighborhood of houses in Seattle, Washington. A bird feeder with a small bird is visible just outside the window, adding a touch of nature to the peaceful setting.",
      poster: '/images/winstonwatchingthehummingbirds.gif'  
      
    },
    {
      id: 12,
      src: '/videos/walkingsora.webm',
      title: "Walking Sora on the Beach front",
      description: "UPDATE!!",
      poster: '/images/walkingsora.gif'  
      
    },
    {
      id: 13,
      src: '/videos/chickensone.mp4',
      title: "Feathered Friends.",
      description: "Three chickens, Ruby, Cheryl, and Barbie, eagerly await their favorite treat: mealworms. Their eyes sparkle with anticipation as they peer through the wire mesh of their coop.",
      poster: '/images/chickensone.jpeg'  
      
    },
    {
      id: 14,
      src: '/videos/winstonatthedogpark.mp4',
      title: "Exploring Seattle's Outdoor Parks at Pamela's Pampered Pets: Active and Engaging Pet Care ",
      description: "A lively scene at a park in Seattle, Washington, featuring winston and his doggy buddy interacting playfully on a dirt path near a tranquil lake.",
      poster: '/images/winstonatthepark.png'  
      
    },
    {
      id: 15,
      src: '/videos/buddyandspencie.mp4',
      title: "Please May I Have Some of Your Breakfast? - A Dogs Plea @ Moclips Washington",
      description: "Meet these adorable Cairn Terriers, a pair of furry friends with captivating personalities. ",
      poster: '/images/buddyandspenciemoclips.gif'  
      
    },
    {
      id: 16,
      src: '/videos/buddyandspencieone.mp4',
      title: "A Brotherly Bond!",
      description: "Two Cairn Terriers, Buddy and Spencie, share a heartwarming moment. Spencie offers comfort and support to Buddy, who appears to be feeling a little down. Their bond is evident in their loving gazes and closeness.",
      poster: '/images/buddyandspencie.gif'  
      
    },
    {
      id: 17,
      src: '/videos/budyandspecietwo.mp4',
      title: "Buddy And Spencie Splashing Good Time!",
      description: "Spencie, a playful Scottish Terrier, enjoys a refreshing dip in the Moclips River. His joyful expression and the ripples caused by his swimming indicate his pure delight in the water.",
      poster: '/images/buddyandspencietwo.jpg'  
      
    },
    {
      id: 18,
      src: '/videos/daisy.mp4',
      title: "Daisy Play Time in Fresh New Snow!",
      description: "UPDATE",
      poster: '/images/daisy.png'
      
    },
    {
      id: 19,
      src: '/videos/walkingthetrailwithbodhiatlincolnpark.mp4',
      title: "Walking The Trail with Bodhi at The Lincoln Park, Seattle!",
      description: "UPDATE",
      poster: '/images/walkingthetrailwithbodhiatlincolnpark.gif'
      
    },
    {
      id: 20,
      src: '/videos/takingthebigdog.mp4',
      title: "Chili, Griffindore and Chancie",
      description: "UPDATE",
      poster: '/images/takingthebigdog.gif'
      
    },
    {
      id: 21,
      src: '/videos/ChilliGriffindoreChance.mp4',
      title: "Chili, Griffindore and Chancie",
      description: "UPDATE",
      poster: '/images/ChilliGriffindoreChance.gif'
      
    },
    {
      id: 22,
      src: '/videos/walkinsoraone.mp4',
      title: "Walking with Sora",
      description: "UPDATE!!  ",
      poster: '/images/walkingsoraone.gif'  
      
    },
    {
      id: 23,
      src: '/videos/carride.mp4',
      title: "Daisy and Vincent",
      description: "UPDATE!!  ",
      poster: '/images/carride.gif'  
      
    },
    {
      id: 24,
      src: '/videos/captain.mp4',
      title: "Captain",
      description: "UPDATE!!  ",
      poster: '/images/captain.gif'  
      
    },
    {
      id: 25,
      src: '/videos/daisyandbear.mp4',
      title: "Daisy & Bear's Tangled Adventure",
      description: "Meet Daisy and Bear, two best friends who turned a simple walk into a memorable adventure. During their daily stroll, these playful pups managed to tangle their leashes, creating a moment of pure, tail-wagging fun. Whether they're exploring new scents or figuring out how to untangle, Daisy and Bear remind me that life’s little mishaps are just part of the journey.",
      poster: '/images/daisyandbear.gif'  
      
    },
    {
      id: 26,
      src: '/videos/GivingJosomepets.mp4',
      title: "Giving Jo some Pets",
      description: "UPDATE!!  ",
      poster: '/images/givingJosomepets.gif'  
      
    },
    {
      id: 27,
      src: '/videos/undercoverdog.mp4',
      title: "Snuggly Under The Cover",
      description: "At Pamela's Pampered Pets, I offer specialized care for your furry companion, ensuring their comfort and well-being. Let me pamper your furry companion. ",
      poster: '/images/picturetwo.png'  
      
    },
    {
      id: 28,
      src: '/videos/kittylounging.mp4',
      title: "Snuggly Under The Cover",
      description: "At Pamela's Pampered Pets, I offer specialized care for your furry companion, ensuring their comfort and well-being. Let me pamper your furry companion. ",
      poster: '/images/kittylounging.gif'  
      
    },

    
  ];

  const photos = [
    {
      id: 1,
      src: "/images/7777.png",
      title: "Compassionate Canine Care at Pamela’s Pampered Pets",
      description: "Experience the pinnacle of pet pampering with Seattle’s own Pamela’s Pampered Pets – Where every animal is treated like family",
      alt:"A well-groomed, robust dog wearing a cozy striped sweater stands on lush green grass, showcasing the attentive and personalized care provided by Pamela’s Pampered Pets in Seattle"
    },
    {
      id: 2,
      src: "/images/144.png",
      title: "Two Dogs Relaxing Comfortably on Cozy Bed",
      description: "A Peaceful moment of two dogs relaxing indoors, highlighting the comfort and companionship pets bring to a home. ",
      subtext:"This image showcases a peaceful moment of two dogs relaxing indoors, highlighting the comfort and companionship pets bring to a home. Ideal for content related to pet care, home decor for pet owners, or the joys of having pets.Two dogs are lying on cushioned beds in a cozy indoor setting. The brown dog on the left rests on a beige cushion with its tongue out, appearing content. The grey dog on the right is lying on a colorful blanket featuring various dog silhouettes, looking directly at the camera. Surrounding them are soft furniture and a calm ambiance.",
      alt:"Two contented dogs lounging comfortably indoors at Pamela’s Pampered Pets, a pet care facility in Seattle. One dog is resting on a beige cushion with its tongue playfully out, while the other lies on a colorful blanket with bone and paw print patterns, symbolizing the attentive and personalized care they receive.",
    },
    {
      id: 3,
      src: "/images/155.png",
      title: "Cozy Afternoon Retreat",
      description: " A well-cared-for pet enjoying a cozy moment. Quality pet care services available in Seattle.",
      alt:"A cute dog with a red blanket wrapped around its head, looking up with a gentle expression, receiving care at Pamela's Pampered Pets in Seattle, WA."
    },
    {
      id: 4,
      src: "/images/14four.png",
      title: "Companions in Stripes: A Canine Duo’s Portrait",
      description: "Two dogs in striped outfits share a moment of camaraderie on a cozy carpet.",
      subtext:"The image captures the bond between two pet dogs, dressed in matching striped attire, highlighting their human-like companionship and the trend of pet fashion.",
      alt:"Two dogs wearing striped shirts sitting on a carpet, one facing away and one looking at the camera.",
    },
    {
      id: 5,
      src: "/images/doggievideoposter.png",
      title: "Canine Co-Pilots: Ready for the Road",
      description: "Two dogs in red outfits eagerly look out the car window, ready for their next adventure.",
      subtext:"These two canine companions, dressed in vibrant red, add a touch of whimsy and warmth to any road trip, showcasing the bond between pets and their owners during travel.",
      alt:"Two dogs in red shirts on a car’s back seat looking out the window.",
    },
     {
      id: 6,
      src: "/images/picturetwo.png",
      title: "Cozy Canine Comfort ",
      description: "A dachshund peeks out from under a plush purple blanket, exuding warmth and relaxation",
      subtext:"The picture capures a moment of contentment, showcasing the simple joy pets find in everyday comforts. It may resonate with viewers who appreciate the companionship and endearing quirks of their furry friends.",
      alt:"A dog under a purple blanket on a chair.",
    },
    {
      id: 7,
      src: "/images/pictureone.png",
      title: "Pensive Pooch: A Moment of Reflection",
      description: "A black and white dog gazes thoughtfully, cradling its chin in a paw",
      subtext:"This image captures a candid moment of a pet that appears to be deep in thought, highlighting the often human-like expressions animals can exhibit.",
      alt:"Black and white dog resting its chin on its paw, looking contemplative.",
    },
    {
      id: 8,
      src: "/images/122.png",
      title: "Curious Canine Companion",
      description: "A watchful dog with striking eyes stands attentively indoors, exuding a mix of alertness and friendliness.",
      subtext:"This image captures the essence of domestic canine companionship, showcasing a dog’s inquisitive nature within the comfort of a home setting. The dog’s attentive gaze suggests a moment of interaction or anticipation.",
      alt:"Dog with distinct markings stands inside a home, looking up expectantly.",
    },
    {
      id: 9,
      src: "/images/11.gif",
      title: "A Pup’s Inquisitive Gaze",
      description: "A black and white dog with a curious expression sits inside a cozy room, surrounded by furniture and books",
      subtext:"This image captures the essence of domestic pet life, highlighting the inquisitive nature of a dog within the familiar confines of its home environment",
      alt:"Dog with a quizzical look in a home setting.",
    },
     {
      id: 10,
      src: "./images/chickensone.gif",
      title: "Chickens Stroll Through the Garden",
      description: "Two beautiful chickens stroll across a brick floor, their feathers glistening in the sunlight. ",
      subtext:"Discover the beauty and diversity of the animal kingdom at Pamela's Pampered Pets. Contact me today to learn more about my services.",
      alt:"Two chickens walking on a brick floor with moss growing between the bricks. The chicken in the foreground is a light brown color with black and white feathers. The chicken in the background is a darker brown color with black and white feathers. Both chickens have red combs on their heads.",
    },

    {
      id: 11,
      src: "./images/daisy.png",
      title: "Winter Whiskers: Daisy Enjoying New Snow at Christmas",
      description: "A cherished holiday moment, featuring Daisy, a beloved pet, as she experiences the wonder of freshly fallen snow during Christmas time. The scene is set in a tranquil garden where the untouched snow blankets the ground, creating a serene winter landscape.",
      subtext:"Daisy’s delight adds magic to Christmas Day.",
      alt:"Close-up of Daisy's nose and whiskers in a snowy garden.",
    },

    {
      id: 12,
      src: "./images/winstonwatchinghummingbirds.png",
      title: " Winston Pet-Watching The HummingBird at their Feeder.",
      description: "A cozy indoor scene featuring winston lying on a bed near a window, looking back towards the camera. Outside the window, vibrant fall foliage in shades of yellow, orange, and red surrounds a neighborhood of houses in Seattle, Washington. A bird feeder with a small bird is visible just outside the window, adding a touch of nature to the peaceful setting.",
      subtext:"Pamela's Pampered Pets offers a comforting, home-like environment for your pets in Seattle, where they can relax and enjoy the beauty of nature, just like home.",
      alt:"A dog resting by a window with a scenic view of colorful autumn trees and houses in Seattle, Washington, with a bird perched on a feeder outside.",
    },

    {
      id: 12,
      src: "./images/winstonatthepark.png",
      title: " Explore Seattle’s Outdoors with Pamela's Pampered Pets: Active and Engaging Pet Care",
      description: "A lively scene at a park in Seattle, Washington, featuring winston and his doggy buddy interacting playfully on a dirt path near a tranquil lake.",
      subtext:"Pamela provides outdoor adventures in Seattle, ensuring your pets enjoy exercise and socialization in a safe, natural environment.",
      alt:"Two dogs playing at an outdoor park near a lake in Seattle, Washington, with a person standing by the water in the background.",
    },
    {
      id: 13,
      src: "./images/buddyandspencie.png",
      title: " Buddy and Spencie Sitting Closely Together on a Carpet Floor",
      description: "Two Cairn Terriers with shaggy fur, one gray and one black, are sitting side by side on a carpet in a cozy living room. Their alert ears and expressive faces show their curious and affectionate nature as they look toward the camera. The furniture and soft lighting in the background add to the warm, homely atmosphere.",
      subtext:"Trustworthy and loving care for your furry family members right in the comfort of their home.",
      alt:"Two Cairn Terriers sitting closely together on a carpeted floor",
    },
    {
      id: 14,
      src: "./images/sophie.png",
      title: "Sophie sitting by a window, basking in the sunlight.",
      description: "Sophie sits on a soft blue blanket by a window, with its body mostly shaved, leaving its fur long around the face and tail. The sunlight streaming through the window highlights the cat’s rich fur colors and casts gentle shadows, creating a warm, peaceful atmosphere. A white bowl sits in the foreground, adding a homey touch to the serene setting.",
      subtext:"Every cat deserves a moment of pure comfort after a fresh groom. Treat your feline friend to the best care.",
      alt:"A long-haired cat with a shaved body sitting by a window, basking in the sunlight.",
    },
    {
      id: 15,
      src: "./images/walkingsora.gif",
      title: "update update",
      description: "Sophie sits on a soft blue blanket by a window, with its body mostly shaved, leaving its fur long around the face and tail. The sunlight streaming through the window highlights the cat’s rich fur colors and casts gentle shadows, creating a warm, peaceful atmosphere. A white bowl sits in the foreground, adding a homey touch to the serene setting.",
      subtext:"Every cat deserves a moment of pure comfort after a fresh groom. Treat your feline friend to the best care.",
      alt:"A long-haired cat with a shaved body sitting by a window, basking in the sunlight.",
    },
    {
      id: 16,
      src: "./images/chickens.png",
      title: "Backyard Bliss - Caring for Your Feathered Friends",
      description: "I provide top-notch care for your feathered friends, ensuring they thrive in a loving and well-maintained environment. Trust me to offer the exceptional attention and quality service your pets deserve.",
      subtext:"Every pet deserves love and attention. My services ensure your feathered friends are always looked after with the utmost care.",
      alt:"Two chickens in a backyard with a bowl of water at pamelas pampered pets",
    },
    {
      id: 16,
      src: "./images/griffin.jpeg",
      title: "Griffin's Moment of Joy",
      description: "Griffin, a cheerful golden dog, looks inquisitively at the camera. His playful expression suggests he's ready for adventure.",
      subtext:"A curious mind and a wagging tail are the hallmarks of a happy pup at pamelas pampered pets.",
      alt:"Griffin's Moment of Joy",
    },
    // {
    //   id: 17,
    //   src: "/images/undercoverdog.png",
    //   title: "Dachshund Peeking Out From Purple Blanket",
    //   description: "Meet this beloved furry friend, enjoying a moment of pure relaxation under a soft purple blanket. This furry companions playful spirit shines through in those curious eyes.",
    //   alt:"Dachshund peeking out from purple blanket at Pamela’s Pampered Pets in Seattle, Washington"
    // },
    
  ];

  const testimonials = [
  {
    "quote": "We adopted Winston in September 2020. We met Pam Marbett in May 2021 and wish we had done so sooner. Pam is a dog parent’s dream. She dog sat, house sat, and walked Winston for much of 2021. Pam also cared for my parent’s 13-year-old dog during our family vacations. She was incredibly attentive, loving, and professional with both dogs. Pam's rapport with the pets was amazing.",
    "author": "Melissa B",
    "image": "/images/aboutimage.png",
    "id": "a0ce1"
  },
  {
    "quote": "Pam was punctual, flexible, reliable, communicative, and fully focused on our dogs. Since moving abroad, we dearly miss Pam’s expert care and highly recommend her. We often talk about how much we miss her and her care for Winston. Pam frequently drove Winston from West Seattle to his favorite off-leash park in Marymoor, spoiling him with specialty treats. She also helped with vet appointments as part of moving Winston internationally. Pam went above and beyond, and we cannot recommend her highly enough!",
    "author": "Melissa B",
    "image": "/images/aboutimage.png",
    "id": "a0ce2"
  },
  {
    "quote":"Pam has cared for our large mixed breed dog on several occasions, and we couldn’t be happier or trust her more. She is very empathetic and fully commits to her role in keeping our pup safe and happy while his humans are away. In fact, on her last visit, I had to ask just what she had been doing daily, because our typically very anxious and reactive dog was the most relaxed we’d ever seen him! Pam is an expert communicator and works hard to ensure our instructions are followed to the letter. You and your pets will be lucky to work with her!",
    "author": "Susan",
    "image": "/images/aboutimage.png",
    "id": "aec01"
  },
  {
    "quote": "Pam is the Mary Poppins of dog sitting! She loves on what she does and takes caring for my dogs very seriously. I don’t think they miss me at all when I’m gone. It is so comforting to know they are being cared for by Pam and I can’t say how much I appreciate her!",
    "author": "Anonymous",
    "image": "/images/aboutimage.png",
    "id": "e9cf"
  },
  {
    "quote": "Pam recently looked after our 2 dogs (including one very elderly dog) and our blue crowned conure. Communication was excellent at all stages. She sent frequent updates, took our young dog on many outings and spoiled them rotten. Our plants were all alive and thriving when we got home and our house was spotless. Cannot recommend Pam highly enough!",
    "author": "Anonymous",
    "image": "/images/aboutimage.png",
    "id": "a729"
  }
];
const slides = [
    { src: "/images/longhappydoggiff.gif", caption: "Happy Moment 1" }
   
  ];
  const openModal = (content) => {
    setModalContent(content);
  };

  const closeModal = () => {
    setModalContent(null);
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-4xl font-bold text-center mb-2">
        My Work in Action
      </h1>
      <p className="text-xl text-center text-gray-600 mb-8">
        See the joy and care I bring to pets and their owners.
      </p>

      <div className="flex justify-center mb-8">
        <Tab
          icon={<PlayIcon className="w-5 h-5 " />}
          label="Videos"
          isActive={activeTab === "videos"}
          onClick={() => setActiveTab("videos")}
        />
        <Tab
          icon={<CameraIcon className="w-5 h-5" />}
          label="Photos"
          isActive={activeTab === "photos"}
          onClick={() => setActiveTab("photos")}
        />
      </div>

      {activeTab === "videos" && (
        <div className=''>
          <div className="mb-8">
            <VideoPlayer autoPlay loop muted src={teachingthedogstoswimwebm} poster={teachingdogstoswimwebmposter} />
          
            <div className=" flex items-center justify-center">
              <h2 className="text-3xl font-bold text-gray-800 bg-[#b2dbff] bg-opacity-50 p-4 rounded">
                Watch these furry friends in action!
              </h2>
            </div>

          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3  gap-8">
            {videos.map((video) => (
              <VideoThumbnail
                key={video.id}
                src={video.poster}
                title={video.title}
                description={video.description}
                onClick={() =>
                  openModal(
                    <div>
                      <VideoPlayer src={video.src} className=''/>
                      <h3 className="text-2xl font-bold mt-4">{video.title}</h3>
                      <p className="text-gray-600">{video.description}</p>
                    </div>
                  )
                }
              />
            ))}
          </div>
        </div>
      )}

      {activeTab === "photos" && (
        <div>
          {/* <div className="relative  mb-8">
            <img
              src="/images/happydoggif.gif"
              alt="Hero"
              className="w-96 h-96 mx-auto rounded-lg"
            />
            <div className="absolute inset-0 flex items-center justify-center">
              <h2 className="text-3xl font-bold text-white bg-black bg-opacity-50 p-4 rounded">
                Moments of Happiness
              </h2>
            </div>
          </div> */}
      <div className="relative mb-8">
      

      <div className="w-full mt-8">
        
          
            <div key='one' className="relative text-center">
              
              <img src='./images/longesthappydoggiff.gif'  className="w-auto h-full object-cover rounded-xl mx-auto" />
              <div className="w-96 h-96 object-cover mx-auto absolute inset-0 flex items-end justify-center rounded-xl bg-black bg-opacity-50">
               
                <h2 className="text-3xl text-center font-bold text-white bg-black rounded-xl bg-opacity-50 p-4 ">
                  Captured Moments of Happiness
                </h2>
              </div>
            </div>
          
      
      </div>
    </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {photos.map((photo) => (
              <PhotoThumbnail
                key={photo.id}
                src={photo.src}
                title={photo.title}
                description={photo.description}
                onClick={() =>
                  openModal(
                    <div>
                      <img
                        src={photo.src}
                        alt={photo.title}
                        className="w-full rounded-lg"
                      />
                      <h3 className="text-2xl font-bold mt-4">{photo.title}</h3>
                      <p className="text-gray-600">{photo.description}</p>
                    </div>
                  )
                }
              />
            ))}
          </div>
        </div>
      )}
      
      

      <Modal isOpen={!!modalContent} onClose={closeModal}>
        {modalContent}
      </Modal>
    </div>
  );
};

export default OurWorkInAction;
