/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Slider from 'react-slick';

const testimonials = [
  {
    "quote": "Pamela helped my family out after we were stranded in Europe by a cancelled flight.She came last minute and took excellent care of our two dogs and our house. We don't know what we would've done without her! While we were stuck, she sent pictures and communicated so we knew that our dogs were in good hands. I would highly recommend her services to anyone.",
    "author": "Anon",
    "image": "/images/winston.png",
    "id": "a0ce1"
  },
  {
    "quote": "Jack had a wonderful time! He loves the beach, wandering new parks, meeting appropriate small new friends... I think he was very enriched during his stay e and I hugely appreciated all the regular photos you shared, just seeing Jack enjoying his lil vacation day-by-day",
    "author": "Kento",
    "image": "/images/14four.png",
    "id": "a0ce1"
  },
  {
    "quote": "We adopted our dear Winston in September 2020. We met Pam Marbett in May 2021 and wish we had done so sooner. Pam is a dog parent’s dream. She dog sat, house sat, and walked Winston for much of 2021. Pam also cared for my parent’s 13-year-old dog during our family vacations. She was incredibly attentive, loving, and professional with both dogs. Pam's rapport with the pets was amazing.",
    "author": "Melissa B",
    "image": "/images/winston.png",
    "id": "a0ce1"
  },
  {
    "quote":"Pam has cared for our large mixed breed dog on several occasions, and we couldn’t be happier or trust her more. She is very empathetic and fully commits to her role in keeping our pup safe and happy while his humans are away. In fact, on her last visit, I had to ask just what she had been doing daily, because our typically very anxious and reactive dog was the most relaxed we’d ever seen him! Pam is an expert communicator and works hard to ensure our instructions are followed to the letter. You and your pets will be lucky to work with her!",
    "author": "Susan",
    "image": "/images/111.png",
    "id": "aec01"
  },
  {
    "quote": "Pam was punctual, flexible, reliable, communicative, and fully focused on our dogs. Since moving abroad, we dearly miss Pam’s expert care and highly recommend her. We often talk about how much we miss her and her care for Winston. Pam frequently drove Winston from West Seattle to his favorite off-leash park in Marymoor, spoiling him with specialty treats. She also helped with vet appointments as part of moving Winston internationally. Pam went above and beyond, and we cannot recommend her highly enough!",
    "author": "Melissa B",
    "image": "/images/winstonatthepark.png",
    "id": "a0ce2"
  },
  {
    "quote": "Pam is the Mary Poppins of dog sitting! She loves on what she does and takes caring for my dogs very seriously. I don’t think they miss me at all when I’m gone. It is so comforting to know they are being cared for by Pam and I can’t say how much I appreciate her!",
    "author": "Mellisa B",
    "image": "/images/155.png",
    "id": "e9cf"
  },
  {
    
    "quote": "Pam recently looked after our 2 dogs (including one very elderly dog) and our blue crowned conure. Communication was excellent at all stages. She sent frequent updates, took our young dog on many outings and spoiled them rotten. Our plants were all alive and thriving when we got home and our house was spotless. Cannot recommend Pam highly enough!",
    "author": "Kento",
    "image": "/images/poser.gif",
    "id": "a729"
  },
  {
    
    "quote": "Pam dog sat for both Winston and my parents' dog during our family vacations. Winston was under a year old, and my parents' dog was 13. Pam cared for them both with love and attention. We were very pleased.",
    "author": "Kento",
    "image": "/images/winston.gif",
    "id": "a729"
  },

  {
    
    "quote": "We adopted Winston in September 2020. We met Pam in May 2021 and wished we had sooner. She's a dog parent's dream. She dog sat, house sat, and dog walked Winston for much of 2021.",
    "author": "Kylee K",
    "image": "/images/poser.gif",
    "id": "a729"
  },
  {
    
    "quote": "We recommend Pam to everyone. We still talk about how much we miss her and what she did for Winston. Pam often drove Winston to his favorite dog park in Marymoor. She spoiled him with treats. She also helped with a vet appointment for our move abroad. Pam was phenomenal with our dog. We highly recommend her!",
    "author": "Kylee K",
    "image": "/images/poser.gif",
    "id": "a729"
  },
  {
    
    "quote": " Pam was always amazing. She had a great rapport with both pets. She was punctual, flexible, reliable, communicative, professional, and focused on our dogs. We've moved abroad and miss her care.",
    "author": "Kylee K",
    "image": "/images/poser.gif",
    "id": "a729"
  },



];

const sliderSettings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 15000,
  };
const Testimonial = () => (
  <section className="relative bg-[#f0f8ff] py-8">
  <div className="absolute top-0 left-0 w-full h-full bg-cover blur-sm rounded-full bg-center opacity-50" style={{ backgroundImage: "url('/images/pawfulheart.png')" }}></div>
  <header className="text-3xl font-bold relative z-10 text-center mb-8  text-gray-900 dark:text-gray-100">
    What Others Are Saying About Pamela
  </header>
  <Slider {...sliderSettings} className="relative  z-10 mx-auto max-w-3xl">
    {testimonials.map(testimonial => (
      <div key={testimonial.id} className="mx-auto w-full sm:w-4/5 lg:w-3/5 bg-white bg-opacity-50 p-8 rounded-lg text-center italic">
        <img src={testimonial.image} alt={testimonial.author} className="mx-auto mb-4 rounded-full w-24 h-24 object-cover" />
        <blockquote className="mb-4 text-gray-800">
          <p className="font-roboto-mono text-lg">{testimonial.quote}</p>
          <footer className="text-lg font-semibold text-gray-600">— {testimonial.author}</footer>
        </blockquote>
      </div>
    ))}
  </Slider>
</section>
);

export default Testimonial;
