/**
 * This code was generated by Builder.io.
 */
import React from "react";

const BookingRow = ({
  booking,
  onDelete,
  onUpdate,
  onToggleExpand,
  isExpanded,
}) => (
  <tr>
    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
      {booking.customerName}
    </td>
    {/* <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
      {booking.startDateAndTime}
    </td> */}
    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
      {new Intl.DateTimeFormat('en-US', {
        weekday: 'long', // e.g., "Monday"
        year: 'numeric', // e.g., "2024"
        month: 'long',   // e.g., "September"
        day: 'numeric',  // e.g., "1"
        hour: 'numeric', // e.g., "4 PM"
        minute: 'numeric', // e.g., "35"
        hour12: true,    // 12-hour format
      }).format(new Date(booking.startDateAndTime))}
    </td>
    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
      {new Intl.DateTimeFormat('en-US', {
        weekday: 'long', // e.g., "Monday"
        year: 'numeric', // e.g., "2024"
        month: 'long',   // e.g., "September"
        day: 'numeric',  // e.g., "1"
        hour: 'numeric', // e.g., "4 PM"
        minute: 'numeric', // e.g., "35"
        hour12: true,    // 12-hour format
      }).format(new Date(booking.endDateAndTime))}
    </td>

    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
      {booking.endDateAndTime}
    </td>
    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
      <button
        onClick={() => onToggleExpand(booking._id)}
        className="text-indigo-600 hover:text-indigo-900"
      >
        {isExpanded ? "Collapse" : "Expand"}
      </button>
    </td>
    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
      <button
        onClick={() => onUpdate(booking._id)}
        className="text-green-600 hover:text-green-900 mr-2"
      >
        Update
      </button>
      <button
        onClick={() => onDelete(booking._id)}
        className="text-red-600 hover:text-red-900"
      >
        Delete
      </button>
    </td>
  </tr>
);

export default BookingRow;
