/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ExpandedBookingDetails = ({ booking }) => (
  <tr>
    <td colSpan="5" className="px-6 py-4">
      <div className="bg-gray-50 p-4 rounded-lg">
        <p>
          <strong>Booking ID:</strong> {booking._id}
        </p>
        <p>
          <strong>Customer Name:</strong> {booking.customerName}
        </p>
        <p>
          <strong>Email:</strong> {booking.email}
        </p>
        <p>
          <strong>Cell Phone:</strong> {booking.cellPhone}
        </p>
        <p>
          <strong>Home Phone:</strong> {booking.homePhone}
        </p>
        <p>
          <strong>Home Address:</strong> {booking.homeAddress}
        </p>
        <p>
          <strong>Emergency Contact Number:</strong>{" "}
          {booking.emergencyContactNumber}
        </p>
        <p>
          <strong>Work Phone:</strong> {booking.workPhone}
        </p>
        <p>
          <strong>Pet's Name:</strong> {booking.petsName}
        </p>
        <p>
          <strong>Pet's Age:</strong> {booking.petsAge}
        </p>
        <p>
          <strong>Daily Routine:</strong> {booking.dailyRoutine}
        </p>
        <p>
          <strong>Health Information:</strong> {booking.petsHealth}
        </p>
        <p>
          <strong>Favorite Things:</strong> {booking.favoriteThings}
        </p>
        <p>
          <strong>Idiosyncrasies:</strong> {booking.idioSyncrasies}
        </p>
        <p>
          <strong>Permission to take to vet:</strong> {booking.vetPermission}
        </p>
        <p>
          <strong>Start Date and Time:</strong> {booking.startDateAndTime}
        </p>
        <p>
          <strong>End Date and Time:</strong> {booking.endDateAndTime}
        </p>
        <p>
          <strong>Special Requests:</strong> {booking.specialRequest}
        </p>
        <p>
          <strong>Alarm Information:</strong> {booking.alarmInfo}
        </p>
        <p>
          <strong>Miscellaneous Notes:</strong> {booking.miscNotes}
        </p>
        <p>
          <strong>Additional Notes:</strong> {booking.additionalNotes}
        </p>
      </div>
    </td>
  </tr>
);

export default ExpandedBookingDetails;
