import axios from 'axios';

const createBookingUrl = 'https://backend-c469.onrender.com/bookings/create';
const getAllBookingsUrl = 'https://backend-c469.onrender.com/bookings/getall';
const updateBookingUrl = 'https://backend-c469.onrender.com/bookings/update';
const removeABookingUrl = 'https://backend-c469.onrender.com/bookings/delete';

const bookingServices = {
  // Create a new booking
  createBooking: async (bookingData) => {
    try {
      const response = await axios.post(createBookingUrl, bookingData);
      return response.data;
    } catch (error) {
      console.error('Error creating booking:', error);
      throw error;
    }
  },

  // Retrieve all bookings
  getAllBookings: async () => {
    try {
      const response = await axios.get(getAllBookingsUrl);
      return response.data;
    } catch (error) {
      console.error('Error fetching bookings:', error);
      throw error;
    }
  },

  // Remove a booking by ID
  removeABooking: async (id) => {
    try {
      const response = await axios.delete(`${removeABookingUrl}/${id}`);
      return response.data;
    } catch (error) {
      console.error('Error deleting booking:', error);
      throw error;
    }
  },

  // Update an existing booking by ID
  updateBooking: async (id, updateData) => {
    try {
      const response = await axios.put(`${updateBookingUrl}/${id}`, updateData);
      return response.data;
    } catch (error) {
      console.error('Error updating booking:', error);
      throw error;
    }
  },
};

export default bookingServices;



/**
 * This code was generated by Builder.io.
 */
// import axios from "axios";

// const API_BASE_URL = "http://localhost:5050/api/bookings";

// const bookingService = {
//   createBooking: async (bookingData) => {
//     try {
//       const response = await axios.post(`${API_BASE_URL}/create`, bookingData);
//       return response.data;
//     } catch (error) {
//       console.error("Error creating booking:", error);
//       throw error;
//     }
//   },

//   getAllBookings: async () => {
//     try {
//       const response = await axios.get(`${API_BASE_URL}/getall`);
//       return response.data;
//     } catch (error) {
//       console.error("Error fetching bookings:", error);
//       throw error;
//     }
//   },

//   removeABooking: async (id) => {
//     try {
//       const response = await axios.delete(`${API_BASE_URL}/delete/${id}`);
//       return response.data;
//     } catch (error) {
//       console.error("Error deleting booking:", error);
//       throw error;
//     }
//   },

//   updateBooking: async (id, bookingData) => {
//     try {
//       const response = await axios.put(
//         `${API_BASE_URL}/update/${id}`,
//         bookingData
//       );
//       return response.data;
//     } catch (error) {
//       console.error("Error updating booking:", error);
//       throw error;
//     }
//   },
// };

// export default bookingService;
